#!/usr/bin/env python3
"""
Compare cutoff study cases using existing probe_output.csv files.

This script expects each cutoff_* case directory to already contain
probe_output.csv (generated by postprocess_sampling or other tools).
"""

import argparse
import os
import glob
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DOWNSTREAM_DIR = os.path.join(os.path.dirname(SCRIPT_DIR), "downstream_velocity")
sys.path.append(DOWNSTREAM_DIR)

from compare_alm import load_alm_data, load_fvw_data, compare_and_plot  # noqa: E402


def main():
    parser = argparse.ArgumentParser(description="Compare cutoff study cases against ALM reference.")
    parser.add_argument("--study-dir", required=True, help="Directory containing cutoff_* cases")
    parser.add_argument("--alm-dir", required=True, help="ALM-LES reference case directory")
    parser.add_argument("--output-dir", default=None, help="Output directory for plots")
    parser.add_argument("--csv-name", default="probe_output.csv",
                        help="CSV name inside each case dir (default: probe_output.csv)")
    args = parser.parse_args()

    case_dirs = sorted(glob.glob(os.path.join(args.study_dir, "cutoff_*")))
    if not case_dirs:
        print(f"No cutoff_* cases found in {args.study_dir}")
        return 1

    alm = load_alm_data(args.alm_dir)

    for case_dir in case_dirs:
        case_name = os.path.basename(case_dir)
        csv_path = os.path.join(case_dir, args.csv_name)
        if not os.path.exists(csv_path):
            print(f"[{case_name}] Missing {args.csv_name}, skipping.")
            continue

        try:
            fvw = load_fvw_data(csv_path)
        except Exception as e:
            print(f"[{case_name}] Failed to load CSV: {e}")
            continue

        out_dir = args.output_dir
        if out_dir is None:
            out_dir = os.path.join(case_dir, "post_processing", "comparison_plots")

        print(f"[{case_name}] Writing plots to {out_dir}")
        compare_and_plot(alm, fvw, output_dir=out_dir)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
